global using Carter;
global using Mapster;
global using MediatR;
global using BuildingBlocks.CQRS;
global using JobService.API.Domains.Models;
global using JobService.API.Infrastructure;
global using FluentValidation;
global using Microsoft.EntityFrameworkCore;
global using JobService.API.Exceptions;
